src_list:
  rtl:
  - i2c_master_ctrl.vhd
  - i2c_master_data.vhd
  - i2c_master_top.vhd
  tb:
  - tb_pkg.vhd
  - tb.vhd
submodules: null
sim:
  top_name: tb
  pat_in: pat_in.txt
  pat_out: pat_out.txt
  dut_out: dut_out.txt
  pat_comp_script: null
  fixed_cases:
  - '00'
  pat_gen_script: null
  generated_cases: null
